### ISSUE TITLE
New version no longer works on amazon elasticbean

### ISSUE THREAD

**Issue by anhquan0412** [pankymathur/fastai-vision-app#3]
Hi,
The previous version (Dec 30) works fine on elasticbean, but the new one does not work. The app is still deployed sucessfully, but the 'Upload and Analyze Image' button has no effect upon clicking on it. Can you take a quick look at this? Thanks!

**Comment by pankajarm** [comment]
Thanks for pointing out, Indeed it was pre existing issue where JS button property was disabled by default, I updated this with correct  JS properties 2 days ago, can you please pull the latest repo?

**Comment by pankajarm** [comment]
Plus, I did test it few hours ago on AWS Beanstalk, and it work fine... LMK if you still face same issue

**Comment by anhquan0412** [comment]
I believe I am on the newest version now (commit on Jan 4 is 'Merge branch master ...') and it still doesn't work on beanstalk. Can you tell me which line of code to change the JS button behavior?

**Comment by pankajarm** [comment]
Under index.html button type property is on page load is "button" instead of "submit" =>

						<button type = "button" id = "submit_btn" class="contact100-form-btn">
							<span>
								Upload & Analyze Image
								<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
							</span>
						</button>

This property changes to "submit" when user upload correctly file image type (which is png and jpeg)
under utility.js =>

function fileChange(e) {

    var file = e.target.files[0];

    if (file.type == "image/jpeg" || file.type == "image/png") {

        // Activate Submit Button
        el('submit_btn').type = "submit";
        document.getElementById('inp_img').value = '';
