### ISSUE TITLE
Image Processing Error

### ISSUE THREAD

**Issue by md598** [pankymathur/fastai-vision-app#4]
When uploading an image, there is an internal server error:
![image](https://user-images.githubusercontent.com/6552442/53636297-46a0be80-3be5-11e9-9bba-2355f609ad39.png)

**Comment by pankajarm** [comment]
Hmm, can you provide important details like which of the platform below from list, you are seeing this error?

    https://render.com
    https://zeit.co/now
    https://azure.microsoft.com/en-us/services/app-service/containers/
    https://getcarina.com/
    https://sloppy.io/en/
    https://giantswarm.io
    https://aws.amazon.com/ecs/
    https://cloud.google.com/cloud-build/docs/
    https://www.digitalocean.com/products/one-click-apps/docker/

clearly, request object in server.py is not able to receive image file bytes from  index.html, which could be the issue of JS not able to process image correctly. 

Hence, please provide more details about the platform you are using, what happened when you use the same code on localhost with docker, etc. to investigate this issue.

**Comment by sq5rix** [comment]
Hi! This is on local machine. 

I resolved the issue. 
The file is >100MB and google asks for confirmation to download, as the virus checking cannot work. 
There is a lot of net discussion about it, and multiple scripts. 
For example:
https://www.matthuisman.nz/2019/01/download-google-drive-files-wget-curl.html

My solution is to move the file away from google drive. 

Tom

**Comment by sq5rix** [comment]
I moved to dropbox and I used the following link:
https://dl.dropboxusercontent.com/s/b0bdpyxxrzgkma3/export.pth?dl=0
It works perfectly!!
Thank you again for great code!

**Comment by pankajarm** [comment]
Sure, anytime, LMK if you still have any further issues.
