### ISSUE TITLE
Internal Server Error - Azure Web App

### ISSUE THREAD

**Issue by guilhermesurek** [pankymathur/fastai-vision-app#6]
Hello,
First, thank for sharing this project.

I'm getting this "Internal Server Error" when hitting the button upload and analyze.

![image](https://user-images.githubusercontent.com/23281984/64576994-5c8bfa80-d351-11e9-9a6c-0b746e5df2eb.png)

Steps to reproduce the error:
1) In VS Code, git clone the project.
2) Build Image: Dockerfile
3) Push the docker image
4) Deploy Image to Azure App Service
5) Browse to app, upload an image and hit upload and analyze

I'm pretty new with docker and azure and I'm trying to figure it out how to solve it. I think could be related to >100 mb problem, but I don't know how to solve it in Azure.

**Comment by pankajarm** [comment]
Hi Guilherme, sorry for the really delayed year-long reply, not sure what was the cause of your issue, ideally you should copy paste log from your server to see the error in details, However, I have updated most of the packages recently and tested functionality, it should be workign now on any docker based hosting provider including Azure.
